package bolt

/*

Pre-0.3.0 compatibility (turtlemonvh/blanket#87; asked for on the phase 4
review of #23).

The claim phase 4 makes to users is one sentence: "an unstamped database is
treated as version 1 and stamped on first open; nothing else changes." That
sentence is worth exactly as much as the test underneath it, so this is
that test — the current binary against a database written the way blanket
wrote them before any of this existed.

The fixture is generated by bolt.WriteLegacyFixtureDatabase; see its
comment for why it is generated rather than a committed .db blob.

*/

import (
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/turtlemonvh/blanket/lib/database"
	"github.com/turtlemonvh/blanket/lib/objectid"
	bolt "go.etcd.io/bbolt"
)

func TestOpensAPre030Database(t *testing.T) {
	path := filepath.Join(t.TempDir(), "blanket.db")
	fixture, err := WriteLegacyFixtureDatabase(path)
	require.NoError(t, err)

	// Before: no meta bucket at all.
	func() {
		db := openRaw(t, path)
		require.NoError(t, db.View(func(tx *bolt.Tx) error {
			assert.Nil(t, tx.Bucket([]byte(BOLTDB_META_BUCKET)), "the fixture must not already have a meta bucket")
			return nil
		}))
		require.NoError(t, db.Close())
	}()

	// Open it the way the server does.
	db := openRaw(t, path)
	DB, err := OpenBlanketBoltDB(db, nil)
	require.NoError(t, err, "a current binary must open a pre-0.3.0 database without ceremony")

	// The meta bucket now exists and reads as version 1.
	v, err := DB.SchemaVersion()
	require.NoError(t, err)
	assert.Equal(t, database.InitialSchemaVersion, v)

	// No backup was taken, because nothing was migrated. A mandatory
	// backup on every first open of every old install would be a nasty
	// surprise on a big database.
	backups, err := ListBackups(DefaultBackupDir(path))
	require.NoError(t, err)
	assert.Empty(t, backups, "opening an unstamped database migrates nothing, so it backs up nothing")

	// The records come back unchanged, with the fields that did not exist
	// yet decoding to their zero values rather than to an error.
	task, err := DB.GetTask(fixture.TaskId)
	require.NoError(t, err)
	assert.Equal(t, "echo_task", task.TypeId)
	assert.Equal(t, "WAITING", task.State)
	assert.Equal(t, "hello from 0.2", task.ExecEnv["MESSAGE"])
	assert.Equal(t, []string{"legacy"}, task.Tags)
	assert.Equal(t, "", task.RunId, "a record predating the fencing token decodes with an empty one")
	assert.Nil(t, task.ExitCode, "…and predating the exit code, with a nil one")
	assert.Zero(t, task.RequeueCount)

	worker, err := DB.GetWorker(fixture.WorkerId)
	require.NoError(t, err)
	assert.Equal(t, 4321, worker.Pid)
	assert.Equal(t, []string{"legacy"}, worker.Tags)
	assert.Zero(t, worker.PidStartTs, "predating pid start times")
	assert.Zero(t, worker.LastHeardTs, "predating heartbeats")
	assert.False(t, worker.Lost)

	// And listing works, which is the path the API and UI take.
	ws, err := DB.GetWorkers()
	require.NoError(t, err)
	require.Len(t, ws, 1)

	ts, n, err := DB.GetTasks(&database.TaskSearchConf{
		Limit:      100,
		SmallestId: objectid.NewObjectIdWithTime(time.Unix(0, 0)),
		LargestId:  objectid.NewObjectIdWithTime(time.Unix(database.FAR_FUTURE_SECONDS, 0)),
	})
	require.NoError(t, err)
	assert.Equal(t, 1, n)
	require.Len(t, ts, 1)
	assert.Equal(t, fixture.TaskId, ts[0].Id)

	// Second open sees a stamped database and still changes nothing.
	require.NoError(t, db.Close())
	db2 := openRaw(t, path)
	DB2, err := OpenBlanketBoltDB(db2, nil)
	require.NoError(t, err)
	v2, err := DB2.SchemaVersion()
	require.NoError(t, err)
	assert.Equal(t, database.InitialSchemaVersion, v2)
	task2, err := DB2.GetTask(fixture.TaskId)
	require.NoError(t, err)
	assert.Equal(t, task, task2)
}
