package upgrade

/*

Offline bundles (turtlemonvh/blanket#23 phase 6).

A bundle is one file containing everything an install needs and nothing it
has to fetch: the binaries for all three platforms, the SHA256SUMS that
covers them, the example task types, the blanket-task-type skill, and a
manifest naming the version. `blanket upgrade --bundle` reads it, and
docs/offline_install.md points at it instead of the four-step "download
these things separately from the same tag, and be careful they match"
recipe it used to give — which is a checklist a human executes, and
therefore a checklist a human gets wrong.

Verification is **identical** to the online path. The bundle is not
trusted for being local: it carries the same SHA256SUMS the release
publishes, generated by the same script, and the binary is checked against
it before it is installed. What the bundle changes is where the bytes come
from, not whether they are checked.

Accepts either a `.tar.gz` or an already-extracted directory. The directory
form is what an air-gapped operator ends up with after unpacking once onto
a share, and refusing it would mean re-tarring a directory to satisfy a
format check.

*/

import (
	"archive/tar"
	"compress/gzip"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// ManifestName is the bundle's manifest file.
const ManifestName = "manifest.json"

// BundleSchema is the manifest schema version.
const BundleSchema = 1

// maxBundleFileBytes caps a single entry extracted from a tarball. The
// largest thing in a bundle is a ~20MB binary; the cap is a decompression-
// bomb guard, not a tuning knob.
const maxBundleFileBytes = 512 << 20

// ManifestBinary describes one binary in a bundle.
type ManifestBinary struct {
	Name   string `json:"name"`
	OS     string `json:"os"`
	Arch   string `json:"arch"`
	SHA256 string `json:"sha256"`
	Size   int64  `json:"size"`
}

// Manifest is the bundle's version statement. It is what makes a bundle
// self-describing: without it, "which version is this tarball?" is
// answerable only by running the binary in it, which is exactly the thing
// an operator is trying to decide whether to do.
type Manifest struct {
	Schema    int              `json:"schema"`
	Version   string           `json:"version"`
	Commit    string           `json:"commit,omitempty"`
	BuiltTs   string           `json:"builtTs,omitempty"`
	Binaries  []ManifestBinary `json:"binaries"`
	Types     []string         `json:"types,omitempty"`
	Skills    []string         `json:"skills,omitempty"`
	Generator string           `json:"generator,omitempty"`
}

// Binary finds a manifest entry by asset name.
func (m Manifest) Binary(name string) (ManifestBinary, bool) {
	for _, b := range m.Binaries {
		if b.Name == name {
			return b, true
		}
	}
	return ManifestBinary{}, false
}

// Bundle is an opened bundle.
type Bundle struct {
	// Root is the directory the bundle's files live in — the extraction
	// directory for a tarball, or the directory itself.
	Root     string
	Manifest Manifest
	Sums     Sums
	// Source is the path the caller passed, for messages.
	Source string

	tempDir string
}

// ParseManifest reads a manifest from bytes.
func ParseManifest(b []byte) (Manifest, error) {
	var m Manifest
	if err := json.Unmarshal(b, &m); err != nil {
		return m, fmt.Errorf("bundle manifest is not readable JSON: %w", err)
	}
	if m.Schema == 0 {
		return m, errors.New("bundle manifest has no schema field")
	}
	if m.Schema > BundleSchema {
		return m, fmt.Errorf("bundle manifest schema %d is newer than this blanket understands (%d)", m.Schema, BundleSchema)
	}
	if strings.TrimSpace(m.Version) == "" {
		return m, errors.New("bundle manifest names no version")
	}
	return m, nil
}

// OpenBundle opens a bundle from a directory or a .tar.gz. Close it when
// done; for a tarball that removes the extraction directory.
func OpenBundle(p string) (*Bundle, error) {
	st, err := os.Stat(p)
	if err != nil {
		return nil, err
	}

	b := &Bundle{Source: p}
	if st.IsDir() {
		b.Root = p
	} else {
		dir, err := os.MkdirTemp("", "blanket-bundle-*")
		if err != nil {
			return nil, err
		}
		if err := extractTarGz(p, dir); err != nil {
			os.RemoveAll(dir)
			return nil, err
		}
		b.tempDir = dir
		root, err := bundleRoot(dir)
		if err != nil {
			os.RemoveAll(dir)
			return nil, err
		}
		b.Root = root
	}

	mb, err := os.ReadFile(filepath.Join(b.Root, ManifestName))
	if err != nil {
		b.Close()
		return nil, fmt.Errorf("%s has no %s; is it a blanket bundle?", p, ManifestName)
	}
	if b.Manifest, err = ParseManifest(mb); err != nil {
		b.Close()
		return nil, err
	}
	if b.Sums, err = ParseSumsFile(filepath.Join(b.Root, SumsAssetName)); err != nil {
		b.Close()
		return nil, fmt.Errorf("%s has no readable %s: %w", p, SumsAssetName, err)
	}
	return b, nil
}

// bundleRoot finds the directory holding manifest.json: either the
// extraction directory itself, or the single top-level directory inside it
// (the shape `tar czf` produces when given a directory).
func bundleRoot(dir string) (string, error) {
	if _, err := os.Stat(filepath.Join(dir, ManifestName)); err == nil {
		return dir, nil
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", err
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		cand := filepath.Join(dir, e.Name())
		if _, err := os.Stat(filepath.Join(cand, ManifestName)); err == nil {
			return cand, nil
		}
	}
	return "", fmt.Errorf("no %s found in the bundle", ManifestName)
}

// BinaryPath is where the named asset sits inside the bundle.
func (b *Bundle) BinaryPath(assetName string) string {
	return filepath.Join(b.Root, assetName)
}

// Close removes anything OpenBundle extracted.
func (b *Bundle) Close() error {
	if b == nil || b.tempDir == "" {
		return nil
	}
	err := os.RemoveAll(b.tempDir)
	b.tempDir = ""
	return err
}

// extractTarGz unpacks src into dir.
//
// Every entry's path is checked against dir before anything is written:
// a tar entry named `../../.ssh/authorized_keys` is a well-known way to
// turn "unpack this archive" into "write anywhere the user can write", and
// the archive here is a file an operator was told to download.
// Symlinks and every other non-regular entry are skipped for the same
// reason — a bundle needs files and directories and nothing else.
func extractTarGz(src, dir string) error {
	f, err := os.Open(src)
	if err != nil {
		return err
	}
	defer f.Close()

	gz, err := gzip.NewReader(f)
	if err != nil {
		return fmt.Errorf("%s is not a gzip file: %w", src, err)
	}
	defer gz.Close()

	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}

		clean := filepath.Clean(filepath.FromSlash(hdr.Name))
		if filepath.IsAbs(clean) || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
			return fmt.Errorf("refusing bundle entry %q: it escapes the extraction directory", hdr.Name)
		}
		dest := filepath.Join(dir, clean)

		switch hdr.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(dest, 0o755); err != nil {
				return err
			}
		case tar.TypeReg:
			if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
				return err
			}
			mode := os.FileMode(hdr.Mode).Perm()
			if mode == 0 {
				mode = 0o644
			}
			out, err := os.OpenFile(dest, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, mode)
			if err != nil {
				return err
			}
			n, err := io.Copy(out, io.LimitReader(tr, maxBundleFileBytes+1))
			out.Close()
			if err != nil {
				return err
			}
			if n > maxBundleFileBytes {
				return fmt.Errorf("bundle entry %q is larger than %d bytes", hdr.Name, int64(maxBundleFileBytes))
			}
		default:
			// Skip symlinks, devices, fifos.
		}
	}
}
