#!/usr/bin/env bash
# Generate SHA256SUMS for the built binaries, and (optionally) an offline
# bundle (turtlemonvh/blanket#23 phase 6).
#
# Two jobs, one script, because the second needs the first and splitting
# them would mean a bundle whose checksums could be generated by a
# different code path than the release's.
#
#   scripts/bundle.sh checksums   -> ./SHA256SUMS over the built binaries
#   scripts/bundle.sh bundle      -> dist/blanket-bundle-<version>.tar.gz
#   scripts/bundle.sh all         -> both (the default)
#
# The release workflow runs this after `make docker-build`, and so can you:
# a release artifact that can only be produced by CI is an artifact nobody
# can check before tagging.
#
# VERSION defaults to whatever `git describe` says, so a local run produces
# a plausibly-named bundle without arguments.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

MODE="${1:-all}"
VERSION="${VERSION:-}"
if [[ -z "$VERSION" ]]; then
    VERSION="$(git describe --tags --always --dirty 2>/dev/null || echo dev)"
fi
DIST="${DIST:-$REPO_ROOT/dist}"

# The three cross-compile outputs `make linux darwin windows` produces.
BINARIES=(
    blanket-linux-amd64
    blanket-darwin-amd64
    blanket-windows-amd64.exe
)

# sha256 of a file, on whichever of the two tools this box has. macOS ships
# shasum and not sha256sum; the toolchain image ships the reverse.
sha256_of() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{print $1}'
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$1" | awk '{print $1}'
    else
        echo "bundle: neither sha256sum nor shasum is available" >&2
        exit 1
    fi
}

# write_sums <output> <dir> <file...>
#
# The standard `sha256sum` format -- `<digest>  <name>` -- with basenames
# only, which is what lib/upgrade.ParseSums keys on.
write_sums() {
    local out="$1"; shift
    local dir="$1"; shift
    : > "$out"
    local f
    for f in "$@"; do
        [[ -f "$dir/$f" ]] || continue
        printf '%s  %s\n' "$(sha256_of "$dir/$f")" "$f" >> "$out"
    done
    if [[ ! -s "$out" ]]; then
        echo "bundle: no binaries found in $dir; run 'make linux darwin windows' first" >&2
        exit 1
    fi
}

do_checksums() {
    write_sums "$REPO_ROOT/SHA256SUMS" "$REPO_ROOT" "${BINARIES[@]}"
    echo "bundle: wrote SHA256SUMS"
    cat "$REPO_ROOT/SHA256SUMS"
}

do_bundle() {
    local name="blanket-bundle-${VERSION}"
    local root="$DIST/$name"

    rm -rf "$root"
    mkdir -p "$root/types" "$root/skills"

    local present=()
    local f
    for f in "${BINARIES[@]}"; do
        if [[ -f "$REPO_ROOT/$f" ]]; then
            cp "$REPO_ROOT/$f" "$root/$f"
            chmod +x "$root/$f"
            present+=("$f")
        fi
    done
    if [[ ${#present[@]} -eq 0 ]]; then
        echo "bundle: no binaries found; run 'make linux darwin windows' first" >&2
        exit 1
    fi

    # The rest of what an offline install needs, so
    # docs/offline_install.md's four-step "download these separately from
    # the same tag, and be careful they match" checklist becomes one file.
    cp "$REPO_ROOT"/examples/types/*.toml "$root/types/" 2>/dev/null || true
    if [[ -d "$REPO_ROOT/.claude/skills/blanket-task-type" ]]; then
        mkdir -p "$root/skills/blanket-task-type"
        cp "$REPO_ROOT/.claude/skills/blanket-task-type/SKILL.md" "$root/skills/blanket-task-type/" 2>/dev/null || true
    fi
    cp "$REPO_ROOT/scripts/install.sh" "$root/install.sh" 2>/dev/null || true
    cp "$REPO_ROOT/scripts/install.ps1" "$root/install.ps1" 2>/dev/null || true

    write_sums "$root/SHA256SUMS" "$root" "${present[@]}"

    # manifest.json -- what makes the bundle self-describing. Without it,
    # "which version is this tarball?" is answerable only by running the
    # binary inside it, which is the thing the operator is deciding whether
    # to do.
    {
        printf '{\n'
        printf '  "schema": 1,\n'
        printf '  "version": "%s",\n' "$VERSION"
        printf '  "commit": "%s",\n' "$(git rev-parse HEAD 2>/dev/null || echo unknown)"
        printf '  "builtTs": "%s",\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        printf '  "generator": "scripts/bundle.sh",\n'
        printf '  "binaries": [\n'
        local i=0
        for f in "${present[@]}"; do
            local os arch
            case "$f" in
                *linux*)   os=linux;   arch=amd64 ;;
                *darwin*)  os=darwin;  arch=amd64 ;;
                *windows*) os=windows; arch=amd64 ;;
                *)         os=unknown; arch=unknown ;;
            esac
            [[ $i -gt 0 ]] && printf ',\n'
            printf '    {"name": "%s", "os": "%s", "arch": "%s", "sha256": "%s", "size": %s}' \
                "$f" "$os" "$arch" "$(sha256_of "$root/$f")" "$(wc -c < "$root/$f" | tr -d ' ')"
            i=$((i + 1))
        done
        printf '\n  ]\n'
        printf '}\n'
    } > "$root/manifest.json"

    tar -czf "$DIST/${name}.tar.gz" -C "$DIST" "$name"
    rm -rf "$root"
    echo "bundle: wrote $DIST/${name}.tar.gz"
}

case "$MODE" in
    checksums) do_checksums ;;
    bundle)    do_bundle ;;
    all)       do_checksums; do_bundle ;;
    *)
        echo "usage: scripts/bundle.sh [checksums|bundle|all]" >&2
        exit 2
        ;;
esac
